POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNwb25nZUJvYiIsImlkIjoiNWYyOTcyNmYwYjE4OTgzMWQzZDE5YzA2IiwiaWF0IjoxNTk3MTUwMzM3fQ.aQcDZFK8YNIQe_SiYDoZx9sGtEPNKw_TH4d2Hy7B2XE

{
    "title": "Fun with frontends 5.1.",
    "author": "Dr Sheldon Cooper",
    "url": "http://fullstackopen.com",
    "likes": 1
}
