POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNwb25nZUJvYiIsImlkIjoiNWYyOTcyNmYwYjE4OTgzMWQzZDE5YzA2IiwiaWF0IjoxNTk2NTY4MDE5fQ.LTbVzNhC1ZfW_N500YN5lhNP9Ywxc_WK3B513l5zPsU

{
    "title": "Testing 4.19. is even more fun!",
    "author": "various, add e to beginnig of token",
    "url": "http://fullstackopen.com",
    "likes": 1
}
